name: Update and deploy

on:
  push:
    branches:
      - 'master'
    paths:
      - 'docs/**'
      - 'projects.yml'    # if config is changed
  schedule:
    - cron: '0 0 1 * *'   # monthly
  workflow_dispatch:      # manually trigger if important

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  # check for changes to projects.yml
  changes:
    runs-on: ubuntu-latest
    outputs:
      projects_changed: ${{ steps.filter.outputs.changed }}

    steps:
      - uses: actions/checkout@v6

      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            changed:
              - 'projects.yml'

  update:
    # update projects if the yml was changed or if this is a scheduled run
    needs: changes
    if: needs.changes.outputs.projects_changed == 'true' || github.event_name != 'push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt

      - name: Run update.py
        env:
          GH_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: python3 update.py

      - name: Commit if changed
        run: | 
          git add docs/projects.json
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -m "Update projects.json"
            git push
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: docs
          path: docs

  deploy:
    # run deploy last
    needs: [changes, update]
    if: always()
    runs-on: ubuntu-latest
    
    environment:
      name: github-pages
    
    steps:
      - name: Checkout (fallback)
        # checkout if update was skipped or failed
        if: needs.update.result != 'success'
        uses: actions/checkout@v6

      - name: Download artifact from update job
        # else use the artifact from update
        if: needs.update.result == 'success'
        uses: actions/download-artifact@v8
        with:
          name: docs
          path: docs
    
      - name: Setup Pages
        uses: actions/configure-pages@v6
    
      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./docs

      - name: Deploy
        uses: actions/deploy-pages@v5
